Addes Portfolios Network
gabricavisyn/its-serverless-architectures pull request #63
Opened 2021-06-10 10:20 UTC by FraCata00

Portfolio Network with user, admin, username, name, surname and age

2021-06-17 16:48 UTC, gabricavisyn requested changes

2021-06-17 16:48 UTC, gabricavisyn commented on FraCata00/_sources/aws_node-rest-api-pattern-services/portfolioNetwork/create.js
> -const uuid = require('uuid');
Esiste una libreria node ID?

2021-06-17 21:08 UTC, FraCata00 commented on FraCata00/_sources/aws_node-rest-api-pattern-services/portfolioNetwork/create.js
> -const uuid = require('uuid');
Certo, ti mando lo screen 
![image](https://user-images.githubusercontent.com/78490028/122472498-f79f1300-cfc0-11eb-8f5b-28d42209583d.png)

2021-06-17 21:10 UTC, FraCata00 commented on FraCata00/_sources/aws_node-rest-api-pattern-services/portfolioNetwork/create.js
> -const uuid = require('uuid');
Ma mi sono accorto di aver sbagliato...al posto di scrivere 'uuid' ho scritto 'ID'🤦🏻‍♂️🤦🏻‍♂️

2021-06-18 14:00 UTC, gabricavisyn approved these changes

2021-06-18 14:00 UTC, merged