create-movie-archive homework
gabricavisyn/its-serverless-architectures pull request #79
Opened 2021-06-23 16:30 UTC by Gaian-pixel

2021-06-25 07:28 UTC, gabricavisyn requested changes

2021-06-25 07:28 UTC, gabricavisyn commented on giorgio-gai/homeworks/create-movie-archive/movies/create.js
> +  if (typeof data.title !== 'string' || typeof data.duration !== 'number') {
Io magari qui controllerei che sia in arrivo il dato relativo alla property "director"

2021-06-25 07:28 UTC, gabricavisyn commented on giorgio-gai/homeworks/create-movie-archive/movies/create.js
> +  const { title, duration } = data;
e qua la aggiungerei in estrazione

2021-06-25 07:28 UTC, gabricavisyn commented on giorgio-gai/homeworks/create-movie-archive/movies/list.js
> +    Key: {
Sei sicuro che una ricerca su Dynamo db si faccia così?

2021-06-25 07:28 UTC, gabricavisyn commented on giorgio-gai/homeworks/create-movie-archive/movies/list.js
> +      id: event.pathParameters.director
Dovrei anche verificare che siano effettivamente in arrivo quelle variabili di ricerca, io potrei anche voler listare tutto senza filtri ;-)

2021-06-25 07:28 UTC, gabricavisyn commented on giorgio-gai/homeworks/create-movie-archive/movies/update.js
> +'use strict';
In questo film l'update del director manca completamente

2021-06-30 09:36 UTC, Gaian-pixel commented on giorgio-gai/homeworks/create-movie-archive/movies/list.js
> +    Key: {
Non so farlo

2021-06-30 09:36 UTC, Gaian-pixel commented on giorgio-gai/homeworks/create-movie-archive/movies/list.js
> +      id: event.pathParameters.director
Non so farlo

2021-06-30 09:49 UTC, Gaian-pixel commented on giorgio-gai/homeworks/create-movie-archive/movies/create.js
> +  if (typeof data.title !== 'string' || typeof data.duration !== 'number') {
modifiche apportate

2021-06-30 09:49 UTC, Gaian-pixel commented on giorgio-gai/homeworks/create-movie-archive/movies/create.js
> +  const { title, duration } = data;
modifiche apportate

2021-06-30 09:50 UTC, Gaian-pixel commented on giorgio-gai/homeworks/create-movie-archive/movies/update.js
> +'use strict';
modifiche apportate

2021-07-08 07:47 UTC, gabricavisyn approved these changes

2021-07-08 07:47 UTC, merged