create-movie-archive homework
gabricavisyn/its-serverless-architectures pull request #80
Opened 2021-06-24 21:09 UTC by albizan

2021-06-25 07:32 UTC, gabricavisyn requested changes

2021-06-25 07:32 UTC, gabricavisyn commented on albizan/homeworks/create-movie-archive/movies/list.js
> +    if(director) {
Bello, ma se dovessi fare il filtro direttamente durante lo scan su DynamoDB?

2021-06-25 07:32 UTC, gabricavisyn commented on albizan/homeworks/create-movie-archive/movies/update.js
> +'use strict';
E qua la gestione dei nuovi campi?

2021-06-25 08:51 UTC, albizan commented
Fixed (_hopefully_)

2021-07-08 07:52 UTC, gabricavisyn approved these changes

2021-07-08 07:52 UTC, merged